# Generated by Django 3.2 on 2021-05-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
