# Generated by Django 3.2 on 2021-05-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210515_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
