# Generated by Django 3.2 on 2021-05-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_points_redeemed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='points_redeemed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
