# Generated by Django 3.2 on 2021-05-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_points'),
        ('rewards', '0002_alter_rewardhistory_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardhistory',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rewards.reward'),
        ),
    ]
