# Generated by Django 3.2 on 2021-05-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rewardhistory_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardhistory',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Reward History'},
        ),
    ]
