# Generated by Django 3.2 on 2021-04-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
