# Generated by Django 3.2 on 2021-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprofile',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
