# Generated by Django 3.2 on 2021-04-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210427_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='value',
        ),
        migrations.AddField(
            model_name='size',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
