# Generated by Django 3.2 on 2021-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210427_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='brand',
            name='available_sizes',
            field=models.ManyToManyField(to='products.Size'),
        ),
    ]
