# Generated by Django 3.2 on 2021-04-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210427_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nicotine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='available_nics',
            field=models.ManyToManyField(to='products.Nicotine'),
        ),
    ]
