# Generated by Django 3.2 on 2021-05-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
