# Generated by Django 3.2 on 2021-05-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210501_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_per_ml',
        ),
        migrations.RemoveField(
            model_name='size',
            name='value',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='nicotine',
            name='type',
            field=models.CharField(blank=True, choices=[('freebase', 'FREEBASE'), ('salt', 'SALT'), ('hybrid', 'HYBRID')], max_length=8, null=True),
        ),
    ]
