# Generated by Django 3.2 on 2021-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210501_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
