# Generated by Django 3.2 on 2021-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210501_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_percentage',
        ),
        migrations.AddField(
            model_name='size',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
