# Generated by Django 3.2 on 2021-05-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productvariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
