# Generated by Django 3.2 on 2021-05-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_delete_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='friendly_name',
        ),
    ]
