# Generated by Django 3.2 on 2021-05-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
