# Generated by Django 3.2 on 2021-05-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20210519_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-pk']},
        ),
    ]
