# Generated by Django 3.2 on 2021-05-31 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-pk']},
        ),
    ]
